# Generated by Django 5.1 on 2024-10-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='ICS23-08-024', max_length=15, unique=True),
        ),
    ]
