# Generated by Django 5.1 on 2024-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0003_event_alter_user_student_id_seat_bookedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
