# Generated by Django 5.1 on 2024-10-15 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0006_event_price_per_seat_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedticket',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='bookedticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='booked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='seat_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='ABhallbooking.event'),
        ),
    ]
