# Generated by Django 5.1 on 2024-10-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0007_remove_bookedticket_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='seat_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookedticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
