# Generated by Django 5.1 on 2024-10-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0009_remove_seat_is_available_seat_booked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
