# Generated by Django 5.1 on 2024-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
