# Generated by Django 5.1 on 2024-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABhallbooking', '0012_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
